version: "3.9"
services:
  web:
    build: .
    container_name: flask_web
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/usersdb
      REDIS_URL: redis://cache:6379/0
    depends_on:
      - db
      - cache
    ports:
      - "5000:5000"

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  cache:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  pgdata:

